pipelines:
  - name: demo_jenkins_integration
    steps:
      - name: test_app
        type: Jenkins
        configuration:
          jenkinsJobName: basic-api
        integrations:
          - name: myJenkins
        outputResources:
          - name: app_test_results
